var mongoose = require('mongoose')

var acordaoSchema = new mongoose.Schema({
    tribunal : String, 
    url : String, 
    Processo : String, 
    Descritores : [String],
    'Votação' : String,
    'Data do Acordão' : String, 
    Relator : String,
    'Texto Integral' : String,
    'Decisão Texto Integral' : String, 
    'Sumário' : String, 
    'Nº Convencional' : String, 
    'Nº do Documento' : String, 
    'Meio Processual' : String, 
    'Decisão' : String, 
    'Recorrido 1' : String,
    Recorrente : String, 
    Tribunal : String, 
    Privacidade : String, 
    'Área Temática 1' : String, 
    'Sub-Secção' : String, 
    'Nº Processo/TAF' : String, 
    Contencioso : String, 
    Data : String,
    Magistrado : String, 
    'Secção' : String, 
    'Indicações Eventuais' : String, 
    'Legislação Nacional' : String, 
    'Normas Apreciadas' : String, 
    'Tribunal 1ª instância' : String, 
    'Data da Decisão' : String, 
    'Tribunal Recurso' : String, 
    'Data de Entrada' : String, 
    'Normas Julgadas Inconst.' : String, 
    'Texto Parcial' : String, 
    'Acordão' : String, 
    'Peça Processual' : String, 
    Requerido : String, 
    Tema : String, 
    Autor : String, 
    'Réu' : String, 
    'Juízo ou Secção' : String, 
    'Área Temática 2' : String, 
    Recursos : String, 
    'Espécie' : String, 
    'Recorrido 2' : String, 
    'Parecer Ministério Publico' : String, 
    'Texto das Cláusulas Abusivas' : String, 
    'Tipo de Contrato' : String, 
    'Tipo de Ação' : String, 
    'Área Temática' : String, 
    'Reclamações' : String, 
    Requerente : String,
    Favorite : Boolean
})

var acordaoModel = mongoose.model('acordao',acordaoSchema)

module.exports.acordaoModel = acordaoModel